spring.datasource.url: jdbc:mysql://localhost:3306/account
spring.datasource.username: root
spring.datasource.password: qwer12#$
spring.jpa.hibernate.dll-auto: update
spring.jpa.properties.hibernate.hbm2ddl.auto: update

#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect